// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emails.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (
    transaction_uuid, consumer, user_name, email_subject, email_text, html,
    sender_name, sender_email, recipients_name, recipients_email,
    status, created_at,
    enable_open_tracking, opened
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING transaction_uuid, consumer, user_name, email_subject, email_text, html, sender_name, sender_email, recipients_name, recipients_email, status, created_at, enable_open_tracking, opened
`

type CreateEmailParams struct {
	TransactionUuid    uuid.UUID
	Consumer           string
	UserName           string
	EmailSubject       sql.NullString
	EmailText          sql.NullString
	Html               sql.NullString
	SenderName         string
	SenderEmail        string
	RecipientsName     string
	RecipientsEmail    string
	Status             string
	CreatedAt          time.Time
	EnableOpenTracking bool
	Opened             bool
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRowContext(ctx, createEmail,
		arg.TransactionUuid,
		arg.Consumer,
		arg.UserName,
		arg.EmailSubject,
		arg.EmailText,
		arg.Html,
		arg.SenderName,
		arg.SenderEmail,
		arg.RecipientsName,
		arg.RecipientsEmail,
		arg.Status,
		arg.CreatedAt,
		arg.EnableOpenTracking,
		arg.Opened,
	)
	var i Email
	err := row.Scan(
		&i.TransactionUuid,
		&i.Consumer,
		&i.UserName,
		&i.EmailSubject,
		&i.EmailText,
		&i.Html,
		&i.SenderName,
		&i.SenderEmail,
		&i.RecipientsName,
		&i.RecipientsEmail,
		&i.Status,
		&i.CreatedAt,
		&i.EnableOpenTracking,
		&i.Opened,
	)
	return i, err
}

const getEmailByTransactionUUID = `-- name: GetEmailByTransactionUUID :one
SELECT
    transaction_uuid, consumer, user_name, email_subject, email_text, html,
    sender_name, sender_email, recipients_name, recipients_email,
    status, created_at,
    enable_open_tracking, opened
FROM emails
WHERE transaction_uuid = $1 AND consumer = $2
`

type GetEmailByTransactionUUIDParams struct {
	TransactionUuid uuid.UUID
	Consumer        string
}

func (q *Queries) GetEmailByTransactionUUID(ctx context.Context, arg GetEmailByTransactionUUIDParams) (Email, error) {
	row := q.db.QueryRowContext(ctx, getEmailByTransactionUUID, arg.TransactionUuid, arg.Consumer)
	var i Email
	err := row.Scan(
		&i.TransactionUuid,
		&i.Consumer,
		&i.UserName,
		&i.EmailSubject,
		&i.EmailText,
		&i.Html,
		&i.SenderName,
		&i.SenderEmail,
		&i.RecipientsName,
		&i.RecipientsEmail,
		&i.Status,
		&i.CreatedAt,
		&i.EnableOpenTracking,
		&i.Opened,
	)
	return i, err
}

const getEmailConsumer = `-- name: GetEmailConsumer :many
SELECT
    transaction_uuid, consumer, user_name, email_subject, email_text, html,
    sender_name, sender_email, recipients_name, recipients_email,
    status, created_at, enable_open_tracking, opened
FROM emails
WHERE consumer = $1
ORDER BY created_at DESC
`

func (q *Queries) GetEmailConsumer(ctx context.Context, consumer string) ([]Email, error) {
	rows, err := q.db.QueryContext(ctx, getEmailConsumer, consumer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.TransactionUuid,
			&i.Consumer,
			&i.UserName,
			&i.EmailSubject,
			&i.EmailText,
			&i.Html,
			&i.SenderName,
			&i.SenderEmail,
			&i.RecipientsName,
			&i.RecipientsEmail,
			&i.Status,
			&i.CreatedAt,
			&i.EnableOpenTracking,
			&i.Opened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailStatus = `-- name: UpdateEmailStatus :exec
UPDATE emails
SET status = $2
WHERE transaction_uuid = $1
`

type UpdateEmailStatusParams struct {
	TransactionUuid uuid.UUID
	Status          string
}

func (q *Queries) UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailStatus, arg.TransactionUuid, arg.Status)
	return err
}
