// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subdomain.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAvailableSubdomain = `-- name: CreateAvailableSubdomain :one
INSERT INTO available_subdomains (name)
VALUES ($1)
RETURNING available_subdomain_uuid, name, created_at, is_default
`

func (q *Queries) CreateAvailableSubdomain(ctx context.Context, name string) (AvailableSubdomain, error) {
	row := q.db.QueryRowContext(ctx, createAvailableSubdomain, name)
	var i AvailableSubdomain
	err := row.Scan(
		&i.AvailableSubdomainUuid,
		&i.Name,
		&i.CreatedAt,
		&i.IsDefault,
	)
	return i, err
}

const createSubdomainOwnership = `-- name: CreateSubdomainOwnership :one
INSERT INTO subdomain_ownerships (subdomain_ownership_uuid, subdomain_id, business_unit)
VALUES ($1, $2, $3)
RETURNING subdomain_ownership_uuid, subdomain_id, business_unit, created_at
`

type CreateSubdomainOwnershipParams struct {
	SubdomainOwnershipUuid uuid.UUID
	SubdomainID            uuid.UUID
	BusinessUnit           string
}

func (q *Queries) CreateSubdomainOwnership(ctx context.Context, arg CreateSubdomainOwnershipParams) (SubdomainOwnership, error) {
	row := q.db.QueryRowContext(ctx, createSubdomainOwnership, arg.SubdomainOwnershipUuid, arg.SubdomainID, arg.BusinessUnit)
	var i SubdomainOwnership
	err := row.Scan(
		&i.SubdomainOwnershipUuid,
		&i.SubdomainID,
		&i.BusinessUnit,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailableSubdomainByName = `-- name: GetAvailableSubdomainByName :one
SELECT available_subdomain_uuid, name, created_at, is_default FROM available_subdomains
WHERE name = $1
`

func (q *Queries) GetAvailableSubdomainByName(ctx context.Context, name string) (AvailableSubdomain, error) {
	row := q.db.QueryRowContext(ctx, getAvailableSubdomainByName, name)
	var i AvailableSubdomain
	err := row.Scan(
		&i.AvailableSubdomainUuid,
		&i.Name,
		&i.CreatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getSubdomainOwnershipByApiKey = `-- name: GetSubdomainOwnershipByApiKey :one
SELECT subdomain_ownership_uuid, subdomain_id, business_unit, created_at FROM subdomain_ownerships
WHERE business_unit = $1
`

func (q *Queries) GetSubdomainOwnershipByApiKey(ctx context.Context, businessUnit string) (SubdomainOwnership, error) {
	row := q.db.QueryRowContext(ctx, getSubdomainOwnershipByApiKey, businessUnit)
	var i SubdomainOwnership
	err := row.Scan(
		&i.SubdomainOwnershipUuid,
		&i.SubdomainID,
		&i.BusinessUnit,
		&i.CreatedAt,
	)
	return i, err
}

const getSubdomainOwnershipBySubdomain = `-- name: GetSubdomainOwnershipBySubdomain :one
SELECT subdomain_ownership_uuid, subdomain_id, business_unit, created_at FROM subdomain_ownerships
WHERE subdomain_id = $1
`

func (q *Queries) GetSubdomainOwnershipBySubdomain(ctx context.Context, subdomainID uuid.UUID) (SubdomainOwnership, error) {
	row := q.db.QueryRowContext(ctx, getSubdomainOwnershipBySubdomain, subdomainID)
	var i SubdomainOwnership
	err := row.Scan(
		&i.SubdomainOwnershipUuid,
		&i.SubdomainID,
		&i.BusinessUnit,
		&i.CreatedAt,
	)
	return i, err
}

const isSubdomainAllowedForConsumer = `-- name: IsSubdomainAllowedForConsumer :one
SELECT EXISTS (
  SELECT 1
  FROM available_subdomains s
  LEFT JOIN subdomain_ownerships o ON s.available_subdomain_uuid = o.subdomain_id AND o.business_unit = $2
  WHERE s.name = $1 AND (o.business_unit IS NOT NULL OR s.is_default = TRUE)
) AS allowed
`

type IsSubdomainAllowedForConsumerParams struct {
	Name         string
	BusinessUnit string
}

func (q *Queries) IsSubdomainAllowedForConsumer(ctx context.Context, arg IsSubdomainAllowedForConsumerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isSubdomainAllowedForConsumer, arg.Name, arg.BusinessUnit)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}
