// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: text_messages.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTextMessage = `-- name: CreateTextMessage :one
INSERT INTO text_messages (
    message_id, consumer, user_name, sender, recipient,
    status, api_key, price, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING message_id, consumer, user_name, sender, recipient, status, api_key, err_code, price, created_at
`

type CreateTextMessageParams struct {
	MessageID uuid.UUID
	Consumer  string
	UserName  string
	Sender    string
	Recipient string
	Status    string
	ApiKey    string
	Price     string
	CreatedAt time.Time
}

func (q *Queries) CreateTextMessage(ctx context.Context, arg CreateTextMessageParams) (TextMessage, error) {
	row := q.db.QueryRowContext(ctx, createTextMessage,
		arg.MessageID,
		arg.Consumer,
		arg.UserName,
		arg.Sender,
		arg.Recipient,
		arg.Status,
		arg.ApiKey,
		arg.Price,
		arg.CreatedAt,
	)
	var i TextMessage
	err := row.Scan(
		&i.MessageID,
		&i.Consumer,
		&i.UserName,
		&i.Sender,
		&i.Recipient,
		&i.Status,
		&i.ApiKey,
		&i.ErrCode,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getTextMessage = `-- name: GetTextMessage :one
SELECT
    message_id, consumer, user_name, sender, recipient,
    price, status, created_at
FROM text_messages
WHERE message_id = $1 AND consumer = $2
`

type GetTextMessageParams struct {
	MessageID uuid.UUID
	Consumer  string
}

type GetTextMessageRow struct {
	MessageID uuid.UUID
	Consumer  string
	UserName  string
	Sender    string
	Recipient string
	Price     string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) GetTextMessage(ctx context.Context, arg GetTextMessageParams) (GetTextMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getTextMessage, arg.MessageID, arg.Consumer)
	var i GetTextMessageRow
	err := row.Scan(
		&i.MessageID,
		&i.Consumer,
		&i.UserName,
		&i.Sender,
		&i.Recipient,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTextMessages = `-- name: GetTextMessages :many
SELECT
    message_id, consumer, user_name, sender, recipient,
    price, status, created_at
FROM text_messages
WHERE consumer = $1
ORDER BY created_at DESC
`

type GetTextMessagesRow struct {
	MessageID uuid.UUID
	Consumer  string
	UserName  string
	Sender    string
	Recipient string
	Price     string
	Status    string
	CreatedAt time.Time
}

// -- name: GetTextMessagesByTransactionUUID :one
// SELECT
//
//	message_id, consumer, user_name, sender, recipient,
//	status, created_at
//
// FROM text_messages
// WHERE message_id = $1 AND consumer = $2;
func (q *Queries) GetTextMessages(ctx context.Context, consumer string) ([]GetTextMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTextMessages, consumer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTextMessagesRow
	for rows.Next() {
		var i GetTextMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Consumer,
			&i.UserName,
			&i.Sender,
			&i.Recipient,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTextMessageStatus = `-- name: UpdateTextMessageStatus :one
UPDATE text_messages
SET status = $3,
    price = $4,
    err_code = $5
WHERE message_id = $1 AND api_key = $2
RETURNING message_id, consumer, user_name, sender, recipient, status, api_key, err_code, price, created_at
`

type UpdateTextMessageStatusParams struct {
	MessageID uuid.UUID
	ApiKey    string
	Status    string
	Price     string
	ErrCode   sql.NullString
}

func (q *Queries) UpdateTextMessageStatus(ctx context.Context, arg UpdateTextMessageStatusParams) (TextMessage, error) {
	row := q.db.QueryRowContext(ctx, updateTextMessageStatus,
		arg.MessageID,
		arg.ApiKey,
		arg.Status,
		arg.Price,
		arg.ErrCode,
	)
	var i TextMessage
	err := row.Scan(
		&i.MessageID,
		&i.Consumer,
		&i.UserName,
		&i.Sender,
		&i.Recipient,
		&i.Status,
		&i.ApiKey,
		&i.ErrCode,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
